export PROMPT_COMMAND=""
eval "$(starship init bash)"

source ~/.bash/config
source ~/.bash/aliases
source ~/.bash/functions
source ~/bin/githelpers

# Add GHC 7.8.4 to the PATH, via https://ghcformacosx.github.io/
export GHC_DOT_APP="/Applications/ghc-7.8.4.app"
if [ -d "$GHC_DOT_APP" ]; then
  export PATH="${HOME}/.cabal/bin:${GHC_DOT_APP}/Contents/bin:${PATH}"
fi
. "$HOME/.cargo/env"
. /Users/carlosgaldino/.profile
