tap "d12frosted/emacs-plus"

brew "awscli"
brew "btop"
brew "curl"
brew "ffmpeg"
brew "fish"
brew "gcc"
brew "git"
brew "git-delta"
brew "go"
brew "graphviz"
brew "imagemagick"
brew "jless"
brew "jq"
brew "libgccjit"
brew "make"
brew "openssl"
brew "pandoc"
brew "ripgrep"
brew "starship"
brew "tree"
brew "vim"

brew "d12frosted/emacs-plus/emacs-plus", args: ["with-imagemagick", "with-modern-doom-icon", "with-native-comp", "with-poll"]

cask "amethyst"
cask "iterm2"
cask "linear-linear"
cask "monodraw"
cask "notion"
cask "obsidian"
cask "slack"
cask "spotify"
cask "ticktick"
cask "zoom"

# vim: set ft=ruby :
